[package]
name = "sample_plugin"
version = "0.1.0"
edition = "2021"

[lib]
crate_type = ["cdylib"]
bench = false

[build-dependencies]
# built = "0.7"

[dependencies]
datarace_plugin_api = { path = "../plugin_api" }
