[package]
name = "datarace_plugin_api"
version = "0.1.0"
edition = "2021"

[lib]
crate_type = ["cdylib"]
bench = false

[build-dependencies]
built = "0.7"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
