use cbindgen::{self, Config, Language};
use built;

use std::{env, path::PathBuf};

fn main() {
    built::write_built_file().expect("Failed to acquire build-time information");
    let crate_dir = env::var("CARGO_MANIFEST_DIR").unwrap();

    let config = if let Ok(conf) = Config::from_file("cbindgen.toml") {
        conf
    } else {
        println!("cargo:warning=cbindgen.toml not found (or corrupted) in plugin_api_lib folder, building with defaults");
        let mut conf = Config::default();
        conf.language = Language::C;
        conf.header = Some("/* This file was generated under fallback default settings. Please readd the /plugin_api_lib/cbindgen.toml */\n/* Important you must set this line for plugin_api_sys to still compile: */\n/* language= \"C\" */".to_string());
        conf.autogen_warning = Some("/* This file is automatically generated during build process through cbindgen. Don't modify this manually! */".to_string());
        conf.no_includes = true;

        conf
    };
    

    // There should be a more elgant way to get the same name as the libary being build
    let lib_name = if cfg!(target_os = "linux") {
        "libdatarace_plugin_api"
    } else {
        "datarace_plugin_api"
    }.to_string();
    
    let output = PathBuf::from(env::var("OUT_DIR").unwrap()).join("../../..").canonicalize().unwrap().join(lib_name + ".h");

    cbindgen::Builder::new()
        .with_crate(crate_dir)
        .with_config(config)
        .generate()
        .expect("Unable to generate bindings")
        .write_to_file(output);
}
